In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=10000

### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6605, 4378, 5581, 4810], [6605, 4378, 5581, 3294], [6605, 6720, 5581, 4742], [6881, 9673, 3887, 5404, 6969], [6881, 9673, 3887, 5404, 3175], [1526, 6605, 1477, 5581, 6959], [2673, 1903, 7569, 5404]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6605 4378 5581 4810]
 [   0    0    0    0 6605 4378 5581 3294]
 [   0    0    0    0 6605 6720 5581 4742]
 [   0    0    0 6881 9673 3887 5404 6969]
 [   0    0    0 6881 9673 3887 5404 3175]
 [   0    0    0 1526 6605 1477 5581 6959]
 [   0    0    0    0 2673 1903 7569 5404]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 168ms/step
[[[ 0.03023691  0.02691796  0.02750615 -0.00272106 -0.02815619
    0.04370186 -0.01653587  0.0372397  -0.01981827  0.04002727]
  [ 0.03023691  0.02691796  0.02750615 -0.00272106 -0.02815619
    0.04370186 -0.01653587  0.0372397  -0.01981827  0.04002727]
  [ 0.03023691  0.02691796  0.02750615 -0.00272106 -0.02815619
    0.04370186 -0.01653587  0.0372397  -0.01981827  0.04002727]
  [ 0.03023691  0.02691796  0.02750615 -0.00272106 -0.02815619
    0.04370186 -0.01653587  0.0372397  -0.01981827  0.04002727]
  [ 0.0405209  -0.0451268   0.01156461  0.04294521  0.02891279
   -0.04517831  0.03249973  0.02159629  0.03375537 -0.00813079]
  [ 0.01583347 -0.02659173  0.00795709  0.0274079   0.02987484
   -0.0294669  -0.02966102  0.03821485 -0.01212339 -0.03792837]
  [-0.03780329 -0.01714165  0.01988186  0.03091195 -0.03498427
   -0.0076797  -0.04577404  0.04604017 -0.0390816   0.00315911]
  [-0.00023124 -0.01243015 -0.04259845  0.04639921 -0.0439

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6605, 4378, 5581, 4810])

In [15]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 20ms/step
[[ 0.03023691  0.02691796  0.02750615 -0.00272106 -0.02815619  0.04370186
  -0.01653587  0.0372397  -0.01981827  0.04002727]
 [ 0.03023691  0.02691796  0.02750615 -0.00272106 -0.02815619  0.04370186
  -0.01653587  0.0372397  -0.01981827  0.04002727]
 [ 0.03023691  0.02691796  0.02750615 -0.00272106 -0.02815619  0.04370186
  -0.01653587  0.0372397  -0.01981827  0.04002727]
 [ 0.03023691  0.02691796  0.02750615 -0.00272106 -0.02815619  0.04370186
  -0.01653587  0.0372397  -0.01981827  0.04002727]
 [ 0.0405209  -0.0451268   0.01156461  0.04294521  0.02891279 -0.04517831
   0.03249973  0.02159629  0.03375537 -0.00813079]
 [ 0.01583347 -0.02659173  0.00795709  0.0274079   0.02987484 -0.0294669
  -0.02966102  0.03821485 -0.01212339 -0.03792837]
 [-0.03780329 -0.01714165  0.01988186  0.03091195 -0.03498427 -0.0076797
  -0.04577404  0.04604017 -0.0390816   0.00315911]
 [-0.00023124 -0.01243015 -0.04259845  0.04639921 -0.04397893  0.02235964
 